# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sports',
            field=models.ManyToManyField(to='sports.Sports'),
        ),
    ]
